// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBapjyD9GcMH1uOpLCo-Ae3degrHMWoB78',
    appId: '1:215243681684:web:ac5857ccab6d6271bd2981',
    messagingSenderId: '215243681684',
    projectId: 'flutter-projeto-p2',
    authDomain: 'flutter-projeto-p2.firebaseapp.com',
    storageBucket: 'flutter-projeto-p2.firebasestorage.app',
    measurementId: 'G-6FXRE7X2M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGAwtfaW2QRFYHhMUEL2xYBKJne2CMTuU',
    appId: '1:215243681684:android:260c64ca8f9011cfbd2981',
    messagingSenderId: '215243681684',
    projectId: 'flutter-projeto-p2',
    storageBucket: 'flutter-projeto-p2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW8iy40KV_0uRTJFVxfF0fF91iBgzovLI',
    appId: '1:215243681684:ios:0e0080ca3a5c8865bd2981',
    messagingSenderId: '215243681684',
    projectId: 'flutter-projeto-p2',
    storageBucket: 'flutter-projeto-p2.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjetoP2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW8iy40KV_0uRTJFVxfF0fF91iBgzovLI',
    appId: '1:215243681684:ios:0e0080ca3a5c8865bd2981',
    messagingSenderId: '215243681684',
    projectId: 'flutter-projeto-p2',
    storageBucket: 'flutter-projeto-p2.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjetoP2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBapjyD9GcMH1uOpLCo-Ae3degrHMWoB78',
    appId: '1:215243681684:web:aaddb94d6582d729bd2981',
    messagingSenderId: '215243681684',
    projectId: 'flutter-projeto-p2',
    authDomain: 'flutter-projeto-p2.firebaseapp.com',
    storageBucket: 'flutter-projeto-p2.firebasestorage.app',
    measurementId: 'G-GBFQN799D5',
  );

}